version: "3.7"

services:
  frontend:
    container_name: react-app
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.dev

    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
