version: "3.7"

services:
  api:
    build:
      context: ./services/backend/
      dockerfile: ./Dockerfile.dev

    env_file:
      - ./services/backend/.env.dev
    command: python -m flask run -h 0.0.0.0
    ports:
      - 5001:5000
    depends_on:
      - db

  web:
    container_name: react-app
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    env_file:
      - ./services/frontend/.env.dev

    ports:
      - "3003:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - "REACT_APP_USERS_SERVICE_URL=http://localhost:5001"

    depends_on:
      - api

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    build:
      context: ./services/backend/project/schema
      dockerfile: Dockerfile.sql.dev
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
